Bloggie.Web/Controllers/AdminTagsController.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bloggie.Web.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly ITagRepository tagRepository;

        public AdminTagsController(ITagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            //Mapping AddTagRequest to Tag domain model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName,
            };


            await tagRepository.AddAsync(tag);

            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            //Use DbContext to read the tags
            var tags = await tagRepository.GetAllAsync();
            return View(tags);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
 
            var tag = await tagRepository.GetAsync(id);
            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };
                return View(editTagRequest);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,
            };

            var updatedTag = await tagRepository.UpdateAsync(tag);
            if (updatedTag != null)
            {
                //Show success notification
            }
            else
            {
                //Show error notification
            }

            //Show success notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });

        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            
            var deleteTag = await tagRepository.DeleteAsync(editTagRequest.Id);
            if (deleteTag != null)
            {
                return RedirectToAction("List");
            }
            else
            {
                //Show an error notification
                return RedirectToAction("Edit", new { id = editTagRequest.Id });
            }
           

        }

    }
}

        

Bloggie.Web/Views/AdminTags/Add.cshtml
@model Bloggie.Web.Models.ViewModels.AddTagRequest
@{

}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add New Tag - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" id="name" asp-for="Name"/>
        </div>

        <div class="mb-3">
            <label class="form-label">Display Name</label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

Bloggie.Web/Views/AdminTags/Edit.cshtml
@model Bloggie.Web.Models.ViewModels.EditTagRequest
@{
}
<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Edit Tags - Admin Functionality</h1>
    </div>
</div>
<div class="container py-5">

    @if(Model != null)
    {
        <form method="post">

            <div class="mb-3">
                <label class="form-label">Id</label>
                <input type="text" id="id" class="form-control" asp-for="Id" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" id="Name" class="form-control" asp-for="Name" />
            </div>

            <div class="mb-3">
                <label class="form-label">DisplayName</label>
                <input type="text" id="displayName" class="form-control" asp-for="DisplayName" />
            </div>

            <div class="mb-3">
                <div class="d-flex">
                    <button type="submit" class="btn btn-dark">Update</button>
                    <button type="submit" class="btn btn-danger ms-2"
                        asp-area=""
                        asp-controller="AdminTags"
                        asp-action="Delete">
                        Delete
                    </button>
                </div>
            </div>

        </form>
    }
    else
    {
        <p>Tag not found</p>
    }




</div>

Bloggie.Web/Views/AdminTags/List.cshtml
@model List<Bloggie.Web.Models.Domain.Tag>
@{
}
<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Show All Tags - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    @if(Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>DisPlay Name</th>
                    <th>DisPlay Name</th>
                    <th>DisPlay Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach( var tag in Model)
                {
                    <tr>
                        <td>@tag.Id</td>
                        <td>@tag.Name</td>
                        <td>@tag.DisplayName</td>
                        <td>
                            <a asp-area="" 
                            asp-controller="AdminTags" 
                            asp-action="Edit"
                            asp-route-id="@tag.Id">Edit</a>
                        </td>
                        <td>
                            <a asp-area=""
                            asp-controller="AdminTags"
                            asp-action="Delete"
                            asp-route-id="@tag.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No tags found!</p>
    }

</div>