Bloggie.Web/Controllers/AdminBlogPostsController.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bloggie.Web.Controllers
{
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IBlogPostRepository blogPostRepository;

        public AdminBlogPostsController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;
            this.blogPostRepository = blogPostRepository;
        }


        [HttpGet]
        public async Task<IActionResult> Add()
        {
            //get tags from repository
          var tags  =  await tagRepository.GetAllAsync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {

            //Map view model to domain model
            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,
            };

            //Map Tags from selected tags
            var selectedTags = new List<Tag>();
            foreach(var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }
            blogPost.Tags = selectedTags;

            await blogPostRepository.AddAsync(blogPost);

            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
           var blogPosts = await blogPostRepository.GetAllAsync();
            return View(blogPosts);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            //Retrive the result from the reponsitory
           var blogPost = await blogPostRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if (blogPost != null)
            {
                //map the domain model into the view model
                var model = new EditBlogPostRequest
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    PageTitle = blogPost.PageTitle,
                    Content = blogPost.Content,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    UrlHandle = blogPost.UrlHandle,
                    ShortDescription = blogPost.ShortDescription,
                    PublishedDate = blogPost.PublishedDate,
                    Visible = blogPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    SelectedTags = blogPost.Tags.Select(x => x.Id.ToString()).ToArray()
                };

                return View(model);

            }
          
            //Pass data to view
            return View(null);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            //map view model back to domain model
            var blogPostDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Content = editBlogPostRequest.Content,
                Author = editBlogPostRequest.Author,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                PublishedDate = editBlogPostRequest.PublishedDate,
                UrlHandle = editBlogPostRequest.UrlHandle,
                Visible = editBlogPostRequest.Visible,
            };

            //Map tags into domain model
            var selectedTags = new List<Tag>();
            foreach (var selectedTag in editBlogPostRequest.SelectedTags)
            {
                if(Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);

                    if(foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            blogPostDomainModel.Tags = selectedTags;

            //Submit information to repository to update
            var updateBlog = await blogPostRepository.UpdateAsync(blogPostDomainModel);

            if(updateBlog != null)
            {
                //Show success notification
                return RedirectToAction("Edit");
            }
            //Show error notification
            return RedirectToAction("Edit");
        }


        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            //Talk to reponsitory to delete this blog post and tags
            var deleteBlogPost = await blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if(deleteBlogPost != null) 
            {
                //Show success notification
                return RedirectToAction("List");
            }

            //Show error notification
            return RedirectToAction("Edit", new {id = editBlogPostRequest.Id });
        }
         
    }
}

Bloggie.Web/Views/AdminBlogPosts/Add.cshtml
@model Bloggie.Web.Models.ViewModels.AddBlogPostRequest
@{
}


<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add New BlogPosts - Admin Functionality</h1>
    </div>
</div>


<div class="container py-5">
    <form method="post">

        <div class="mb-3">
            <label class="form-label">Heading</label>
            <input type="text" class="form-control" id="heading" asp-for="Heading"/>
        </div>

        <div class="mb-3">
            <label class="form-label">Page Title</label>
            <input type="text" class="form-control" id="pageTitle" asp-for="PageTitle" />
        </div>

        <div class="mb-3">
            <label class="form-label">Content</label>
            <textarea class="form-control" id="content" asp-for="Content"></textarea>
        </div>

        <div class="mb-3">
            <label class="form-label">Short Description</label>
            <input type="text" class="form-control" id="shortDescription" asp-for="ShortDescription" />
        </div>

        <div class="mb-3">
            <label class="form-label">Featured Image URL</label>
            <input type="text" class="form-control" id="featuredImageUrl" asp-for="FeaturedImageUrl" />
        </div>

        <div class="mb-3">
            <label class="form-label">URL Handle</label>
            <input type="text" class="form-control" id="urlHandle" asp-for="UrlHandle" />
        </div>

        <div class="mb-3">
            <label class="form-label">Published Date</label>
            <input type="date" class="form-control" id="publishedDate" asp-for="PublishedDate" />
        </div>

        <div class="mb-3">
            <label class="form-label">Author</label>
            <input type="text" class="form-control" id="author" asp-for="Author" />
        </div>

        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" value="" id="visible" asp-for="Visible">
            <label class="form-check-label" for="flexCheckDefault">
              Is Visible?
            </label>
        </div>

        <div class="mb-3">
            <label class="form-label">Tags</label>
            <select class="form-select" 
                    asp-items="@Model.Tags"
                    asp-for="SelectedTags"
            ></select>
        </div>

        <div class="mb-3">  
            <button type="submit" class="btn btn-dark">Save</button>
        </div>

    </form>


</div>

Bloggie.Web/Views/AdminBlogPosts/Edit.cshtml
@model Bloggie.Web.Models.ViewModels.EditBlogPostRequest
@{
}
<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Edit BlogPosts - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    @if (Model != null)
    {
        <form method="post">

            <div class="mb-3">
                <label class="form-label">Id</label>
                <input type="text" class="form-control" id="id" asp-for="Id" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="Heading" />
            </div>

            <div class="mb-3">
                <label class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="PageTitle" />
            </div>

            <div class="mb-3">
                <label class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="Content"></textarea>
            </div>

            <div class="mb-3">
                <label class="form-label">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="ShortDescription" />
            </div>

            <div class="mb-3">
                <label class="form-label">Featured Image URL</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="FeaturedImageUrl" />
            </div>

            <div class="mb-3">
                <label class="form-label">URL Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="UrlHandle" />
            </div>

            <div class="mb-3">
                <label class="form-label">Published Date</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="PublishedDate" />
            </div>

            <div class="mb-3">
                <label class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="Author" />
            </div>

            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" value="" id="visible" asp-for="Visible">
                <label class="form-check-label" for="flexCheckDefault">
                    Is Visible?
                </label>
            </div>

            <div class="mb-3">
                <label class="form-label">Tags</label>
                <select class="form-select"
                    asp-items="@Model.Tags"
                    asp-for="SelectedTags"></select>
            </div>

            <div class="mb-3 d-flex">
                <button type="submit" class="btn btn-dark">Update</button>
                <button type="submit" class="btn btn-danger ms-2"
                asp-area=""
                asp-controller="AdminBlogPosts"
                asp-action="Delete"
                >Delete</button>
            </div>

        </form>
    }
    else
    {
        <p>No blog post found!</p>
    }

</div>

Bloggie.Web/Views/AdminBlogPosts/List.cshtml
@model List<Bloggie.Web.Models.Domain.BlogPost>

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>All BlogPosts - Admin Functionality</h1>
    </div>
</div>

<div class="container py-5">
    @if(Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Heading</td>
                    <td>Tag</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var blogPosts in Model)
                {
                    <tr>
                        <td>@blogPosts.Id</td>
                        <td>@blogPosts.Heading</td>
                        <td>
                            <div class="d-flex">
                                @foreach (var tag in blogPosts.Tags)
                                {
                                    <span class="badge bg-secondary me-1">@tag.Name</span>
                                }
                            </div>
                        </td>
                        <td>
                            <a asp-area=""
                       asp-controller="AdminBlogPosts"
                       asp-action="Edit"
                       asp-route-id="@blogPosts.Id">
                                Edit
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Blog Posts Found!</p>
    }
</div>